# Generated by Django 6.0.1 on 2026-01-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_source', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsource',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobsource',
            name='type',
            field=models.CharField(default='website', max_length=50),
        ),
    ]
