# Generated by Django 6.0.1 on 2026-01-11 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_source', '0002_jobsource_active_jobsource_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('url', models.URLField(max_length=500)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_source.jobsource')),
            ],
        ),
    ]
